compile:	
	# Class Conta Corrente
	g++ -Wall -g -c ./ContaCorrente/ContaCorrente.cpp
	# class Correntista
	g++ -Wall -g -c ./Correntista/Correntista.cpp
	# Class Banco
	g++ -Wall -g -c ./Banco/Banco.cpp

	# Main
	g++ -Wall -g -c main.cpp
	g++ -g ContaCorrente.o Correntista.o Banco.o main.o -lm -o main
