# Compile the Class and Main files
compile:
	# Classes
	g++ -Wall -g -c ./classes/OverloadingSumMethod.cpp

	# Main
	g++ -Wall -g -c main.cpp

	# Geral
	g++ -g OverloadingSumMethod.o main.o -lm -o main