# Compile the Class and Main files
compile:
	g++ -Wall -g -c Usuario.cpp
	g++ -Wall -g -c Aluno.cpp
	g++ -Wall -g -c Funcionario.cpp

	g++ -Wall -g -c main.cpp
	g++ -g Usuario.o Aluno.o Funcionario.o main.o -lm -o main