# Class Conta Corrente
compile:	
	g++ -Wall -g -c ./ContaCorrente/ContaCorrente.cpp
	g++ -Wall -g -c ./Correntista/Correntista.cpp

	g++ -Wall -g -c main.cpp
	g++ -g ContaCorrente.o Correntista.o main.o -lm -o main