# Compile the Class and Main files
compile:
	g++ -Wall -g -c Conta.cpp
	g++ -Wall -g -c ContaCorrente.cpp
	g++ -Wall -g -c ContaPoupanca.cpp
	g++ -Wall -g -c main.cpp
	g++ -g Conta.o ContaCorrente.o ContaPoupanca.o main.o -lm -o main